// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(GreenHouseDbContext))]
    [Migration("20220507152542_changeTemperatureToFloat")]
    partial class changeTemperatureToFloat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Models.DioxideCarbonMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Co2Measurement")
                        .HasColumnType("float");

                    b.Property<string>("GreenHouseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GreenHouseId");

                    b.ToTable("DioxideCarbonMeasurement");
                });

            modelBuilder.Entity("Data.Models.Greenhouse", b =>
                {
                    b.Property<string>("GreenHouseId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GreenHouseId");

                    b.ToTable("Greenhouses");
                });

            modelBuilder.Entity("Data.Models.HumidityMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GreenHouseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GreenHouseId");

                    b.ToTable("HumidityMeasurement");
                });

            modelBuilder.Entity("Data.Models.LuminosityMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GreenHouseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsLit")
                        .HasColumnType("bit");

                    b.Property<int>("Lux")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GreenHouseId");

                    b.ToTable("LuminosityMeasurement");
                });

            modelBuilder.Entity("Data.Models.Pot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GreenHouseId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GreenHouseId");

                    b.ToTable("Pot");
                });

            modelBuilder.Entity("Data.Models.TemperatureMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GreenHouseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GreenHouseId");

                    b.ToTable("TemperatureMeasurement");
                });

            modelBuilder.Entity("Data.Models.DioxideCarbonMeasurement", b =>
                {
                    b.HasOne("Data.Models.Greenhouse", null)
                        .WithMany("Co2Measurements")
                        .HasForeignKey("GreenHouseId");
                });

            modelBuilder.Entity("Data.Models.HumidityMeasurement", b =>
                {
                    b.HasOne("Data.Models.Greenhouse", null)
                        .WithMany("HumidityMeasurements")
                        .HasForeignKey("GreenHouseId");
                });

            modelBuilder.Entity("Data.Models.LuminosityMeasurement", b =>
                {
                    b.HasOne("Data.Models.Greenhouse", null)
                        .WithMany("LuminosityMesurments")
                        .HasForeignKey("GreenHouseId");
                });

            modelBuilder.Entity("Data.Models.Pot", b =>
                {
                    b.HasOne("Data.Models.Greenhouse", null)
                        .WithMany("Pots")
                        .HasForeignKey("GreenHouseId");
                });

            modelBuilder.Entity("Data.Models.TemperatureMeasurement", b =>
                {
                    b.HasOne("Data.Models.Greenhouse", null)
                        .WithMany("TemperatureMesurments")
                        .HasForeignKey("GreenHouseId");
                });

            modelBuilder.Entity("Data.Models.Greenhouse", b =>
                {
                    b.Navigation("Co2Measurements");

                    b.Navigation("HumidityMeasurements");

                    b.Navigation("LuminosityMesurments");

                    b.Navigation("Pots");

                    b.Navigation("TemperatureMesurments");
                });
#pragma warning restore 612, 618
        }
    }
}
