# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     
      - name: Git setup
        uses: actions/checkout@v2
      
      - name: Dotnet run
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0' # SDK Version to use; x will use the latest version of the 3.1 channel
      
      - name: Publish prod
        run: cd [yourAppFolder]; dotnet restore; dotnet publish -r linux-x64 --configuration "Release" --self-contained "true" -o ../site;

      - name: Generate deployment package 
        run: cd site; zip ../site.zip *;

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APPLICATION_NAME }}
          environment_name: ${{ env.ENVIRONMENT_NAME }}
          version_label: ${{ github.run_id }}
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy.zip
